# Catppuccin
# Theme create by: https://github.com/AnshumanNeon
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-mocha"

# ========= Border =========
file_panel_border = "##fffbbe"
sidebar_border = "#1e1e2e"
footer_border = "#fffbbe"

# ========= Border Active =========
file_panel_border_active = "#7e5cad"
sidebar_border_active = "#f38ba8"
footer_border_active = "#e4b1f0"
modal_border_active = "#52575d"

# ========= Background (bg) =========
full_screen_bg = "#1e1e2e"
file_panel_bg = "#1e1e2e"
sidebar_bg = "#1e1e2e"
footer_bg = "#1e1e2e"
modal_bg = "#1e1e2e"

# ========= Foreground (fg) =========
full_screen_fg = "#7e5cad"
file_panel_fg = "#7e5cad"
sidebar_fg = "#7e5cad"
footer_fg = "#7e5cad"
modal_fg = "#7e5cad"

# ========= Special Color =========
cursor = "#fffbbe"
correct = "#E1AFD1"
error = "#f38ba8"
hint = "#ffe6e6"
cancel = "#eba0ac"
# Gradient color can only have two color!
gradient_color = ["#fffbbe", "#cba6f7"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#E1AFD1"
file_panel_top_path = "#e4b1f0"
file_panel_item_selected_fg = "#e4b1f0"
file_panel_item_selected_bg = "#1e1e2e"

# ========= Sidebar Special Items =========
sidebar_title = "#e4b1f0"
sidebar_item_selected_fg = "#e4b1f0"
sidebar_item_selected_bg = "#1e1e2e"
sidebar_divider = "#52575d"

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = "#e1afd1"

modal_confirm_fg = "#383838"
modal_confirm_bg = "#cb9df0"

# ========= Help Menu =========
help_menu_hotkey = "#cb9df0"
help_menu_title = "#e1afd1"
