github.com:
    users:
        Ezekiel0108:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Ezekiel0108
